### ISSUE TITLE
Stack trace is output for unmanaged accounts in threading module

### ISSUE THREAD

**Issue by ccdale** [ConnectedHomes/chaim#17]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/linuxbrew/.linuxbrew/opt/python/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mark/.local/lib/python3.7/site-packages/cca/chaimcli.py", line 90, in renewSection
    raise UnmanagedAccount("ignoring " + section + " as it is not managed by cca")
cca.chaimcli.UnmanagedAccount: ignoring dev as it is not managed by cca
```
when encountering an unmanaged section in ~/.aws/credentials
```
[anyname]
aws_access_key_id = AKIAxxxOYZxxx7KQDxxx
aws_secret_access_key = REDACTED
```

**Comment by ccdale** [comment]
fixed in v2.5.3 within threaded section
